### ISSUE TITLE
Create example module

### ISSUE THREAD

**Issue by MALPI** [zalando-incubator/failsafe-actuator#41]
Separate the `FailsafeSampleApp` from the library by moving it to a dedicated module.

It would be nice to have an example Application which one can checkout and run locally. By curling on `localhost:8080/failsafe`, output of the actuator can be seen. Furthermore one could easily see how to use the lib.

**Comment by Iakobs** [comment]
Hi! I am working on that with my colleague!

**Comment by MALPI** [comment]
Hey @lakobs, thanks but there is already a PR for that by @robvanderleek

**Comment by MALPI** [comment]
@lakobs #47 seems still to be free of you Like.

**Comment by MALPI** [comment]
@Iakobs

**Comment by Iakobs** [comment]
Ok @MALPI, I didn't see that!! thank you!
