### ISSUE TITLE
Add support for Spring Boot 2.x

### ISSUE THREAD

**Issue by duergner** [zalando-incubator/failsafe-actuator#43]
The current version is not compatible with Spring Boot 2.x as e.g. `FailsafeAutoConfiguration` is relying on `org.springframework.boot.bind.RelaxedPropertyResolver` which is removed in Spring Boot 2.x

**Comment by duergner** [comment]
https://github.com/spring-projects/spring-boot/wiki/Migrating-a-custom-Actuator-endpoint-to-Spring-Boot-2 has some additional information on how to migrate endpoint definition to Spring Boot 2.x

**Comment by MALPI** [comment]
Thanks for raising this issue @duergner. We are still running Spring Boot 1.x. Still I see the point. I will mark this issue as Help Wanted for the beginning. Maybe someone wants to contribute.

**Comment by duergner** [comment]
Agree - maybe it's better to address this anyway after https://github.com/zalando-incubator/failsafe-actuator/pull/39 has been merged.

**Comment by vpondala** [comment]
Can I look into this?

**Comment by MALPI** [comment]
Yes @vpondala, feel free to take it. Just out of curiosity how was this issue brought to your attention?

**Comment by vpondala** [comment]
@MALPI I've just started to contribute to open source and was looking to work on some starter type issues. As I am right now working on Spring Boot (and migrations), this looked like a perfect fit.

**Comment by vpondala** [comment]
@MALPI I've added support for SpringBoot 2 (2.0.0.M5). I think we would want to merge these changes to a new feature branch. Could you please create a feature branch for me to submit the pull request against?

**Comment by MALPI** [comment]
@vpondala much appreciated! I created the branch "feature/spring-boot-2" for you. Did you got attention to it by "Hacktoberfest"?

**Comment by vpondala** [comment]
@MALPI Yes, #Hacktoberfest motivated me to do some open source :) Submitted the PR now, however I've not bumped the version yet.

**Comment by vpondala** [comment]
Spring boot 2.0.M7 is out now and there are changes to Actuator endpoints.
Can I send a PR?

**Comment by MALPI** [comment]
Hey @vpondala feel free, PR is very welcome. Please also file an issue and describe what needs to be adapted then.
