### ISSUE TITLE
Use Spring mechanisms to instantiate CircuitBreaker

### ISSUE THREAD

**Issue by MALPI** [zalando-incubator/failsafe-actuator#45]
In order to get rid of `CircuitBreakerRegistry` we should make use of Spring mechanisms and implement Springs `FactoryBean` to instantiate a `CircuitBreaker`. 

To get reference to a `CircuitBreaker` we should use `applicationContext.getBean(id, CircuitBreaker.class);`.

**Comment by clarenced** [comment]
Hi @MALPI can I tackle this issue ?

**Comment by MALPI** [comment]
Hey @clarenced feel free!

**Comment by clarenced** [comment]
Hey @MALPI, after implementing a factoryBean, how can we link the new instantiated CircuitBreaker with the bean name in the annotation value ? 

https://github.com/zalando-incubator/failsafe-actuator/blob/master/src/main/java/org/zalando/failsafeactuator/config/FailsafeInjectionConfiguration.java#L37

I don't know if I am the right way, but what I have done is something similar : 

```
    CircuitBreakerFactory circuitBreakerFactory = new CircuitBreakerFactory();
    AutowireCapableBeanFactory factory = applicationContext.getAutowireCapableBeanFactory();
    (CircuitBreaker) factory.initializeBean(circuitBreakerFactory.getObject(), annotation.value());
```
Am I in the correct way ?
