### ISSUE TITLE
Fallback methods for specific exceptions only

### ISSUE THREAD

**Issue by the-dalee** [zalando-incubator/failsafe-actuator#59]
The user should be able to specific for what kind of exceptions the fallback method will be executed. 

**Example use case:**
HttpClientException with status code 404 from upstream dependency may indicate that the data provided by the user of your service is not valid. In this case, the exception is expected and should be handled directly instead of triggering fallback method that may provide outdated or inaccurate data.

**Comment by MALPI** [comment]
hey @the-dalee in general the `Fallback` can also call another Method in case it's a specific `Exception`. Furthermore this rather seems to be a question related to [Failsafe](https://github.com/jhalterman/failsafe#fallbacks) itself and not Failsafe Actuator specific.
